#pragma once

#define MENGINE_API_VERSION UINT32_C(100)

#define MENGINE_CONFIG_MULTITHREADED 0

#define MENGINE_CONFIG_MAX_ENTITIES 100
#define MENGINE_CONFIG_MAX_COMPONENTS 100
#define MENGINE_CONFIG_MAX_COMPONENT_TYPE 100
#define MENGINE_CONFIG_MAX_COMPONENTS_PER_TYPE 100
#define MENGINE_CONFIG_MAX_COMPONENTS_PER_ENTITY 100

#define MENGINE_CONFIG_MAX_GEOMETRY_ASSETS 100
#define MENGINE_CONFIG_MAX_SHADER_ASSETS 100

// @todo Should be auto generated
#define MENGINE_REV_NUMBER 8546
#define MENGINE_REV_SHA1 "878767e751e332309369beecb83e86494f90f8fa"

// @todo check if MENGINE_CONFIG_DEBUG is, else throw error