#ifndef MENGINE_CONFIG_H_HEADER_GUARD
#define MENGINE_CONFIG_H_HEADER_GUARD

#ifndef MENGINE_CONFIG_MULTITHREADED
#define MENGINE_CONFIG_MULTITHREADED 0
#endif

// # Configuration options for mengine.
//
// Any of `MENGINE_CONFIG_*` options that's inside `#ifndef` block can be configured externally
// via compiler options.

#ifndef MENGINE_CONFIG_MAX_ENTITIES
#define MENGINE_CONFIG_MAX_ENTITIES 10000
#endif

#ifndef MENGINE_CONFIG_MAX_COMPONENTS
#define MENGINE_CONFIG_MAX_COMPONENTS 10000
#endif

#ifndef MENGINE_CONFIG_MAX_COMPONENTS_PER_TYPE
#define MENGINE_CONFIG_MAX_COMPONENTS_PER_TYPE 10000
#endif

#ifndef MENGINE_CONFIG_MAX_COMPONENTS_PER_ENTITY
#define MENGINE_CONFIG_MAX_COMPONENTS_PER_ENTITY 10000
#endif

#ifndef MENGINE_CONFIG_MAX_ENTITIES_TO_QUERY
#define MENGINE_CONFIG_MAX_ENTITIES_TO_QUERY 10000
#endif 

#ifndef MENGINE_CONFIG_MAX_GEOMETRY_ASSETS
#define MENGINE_CONFIG_MAX_GEOMETRY_ASSETS 1000
#endif

#ifndef MENGINE_CONFIG_MAX_SHADER_ASSETS
#define MENGINE_CONFIG_MAX_SHADER_ASSETS 1000
#endif

#ifndef MENGINE_CONFIG_MAX_TEXTURE_ASSETS
#define MENGINE_CONFIG_MAX_TEXTURE_ASSETS 1000
#endif

#ifndef MENGINE_CONFIG_MAX_MATERIAL_ASSETS
#define MENGINE_CONFIG_MAX_MATERIAL_ASSETS 1000
#endif

#ifndef MENGINE_CONFIG_MAX_ASSETPACKS
#define MENGINE_CONFIG_MAX_ASSETPACKS 10
#endif

#endif // MENGINE_CONFIG_H_HEADER_GUARD