#ifndef MARA_CONFIG_H_HEADER_GUARD
#define MARA_CONFIG_H_HEADER_GUARD

#ifndef MARA_CONFIG_MULTITHREADED
#define MARA_CONFIG_MULTITHREADED 0
#endif

// # Configuration options for mara.
//
// Any of `MARA_CONFIG_*` options that's inside `#ifndef` block can be configured externally
// via compiler options.

#ifndef MARA_CONFIG_MAX_PAKS
#define MARA_CONFIG_MAX_PAKS 10
#endif

#ifndef MARA_CONFIG_MAX_PAK_ENTRIES
#define MARA_CONFIG_MAX_PAK_ENTRIES 10000
#endif

#ifndef MARA_CONFIG_MAX_RESOURCES
#define MARA_CONFIG_MAX_RESOURCES 10000
#endif

#ifndef MARA_CONFIG_MAX_COMPONENTS
#define MARA_CONFIG_MAX_COMPONENTS 10000
#endif

#ifndef MARA_CONFIG_MAX_ENTITIES
#define MARA_CONFIG_MAX_ENTITIES 10000
#endif

#ifndef MARA_CONFIG_MAX_COMPONENTS_PER_TYPE
#define MARA_CONFIG_MAX_COMPONENTS_PER_TYPE 10000
#endif

#ifndef MARA_CONFIG_MAX_COMPONENTS_PER_ENTITY
#define MARA_CONFIG_MAX_COMPONENTS_PER_ENTITY 10000
#endif

#ifndef MARA_CONFIG_MAX_ENTITIES_TO_QUERY
#define MARA_CONFIG_MAX_ENTITIES_TO_QUERY 10000
#endif 

#ifndef MARA_CONFIG_MAX_GEOMETRIES
#define MARA_CONFIG_MAX_GEOMETRIES 1000
#endif

#ifndef MARA_CONFIG_MAX_SHADERS
#define MARA_CONFIG_MAX_SHADERS 1000
#endif

#ifndef MARA_CONFIG_MAX_TEXTURES
#define MARA_CONFIG_MAX_TEXTURES 1000
#endif

#ifndef MARA_CONFIG_MAX_MATERIALS
#define MARA_CONFIG_MAX_MATERIALS 1000
#endif

#ifndef MARA_CONFIG_MAX_MESHES
#define MARA_CONFIG_MAX_MESHES 1000
#endif

#ifndef MARA_CONFIG_MAX_GEOMETRIES_PER_MESH
#define MARA_CONFIG_MAX_GEOMETRIES_PER_MESH 100
#endif

#ifndef MARA_CONFIG_MAX_UNIFORMS_PER_SHADER
#define MARA_CONFIG_MAX_UNIFORMS_PER_SHADER 16
#endif

#endif // MARA_CONFIG_H_HEADER_GUARD